### ISSUE TITLE
new Test dependency on a @testitem is not found until restart

### ISSUE THREAD

**Issue by lmiq** [julia-vscode/TestItems.jl#9] opened 2022-09-09 13:52 UTC
I am not sure how general is this behavior. But what happened is this: I added a new `@testitem` block, and in this particular item I needed a new test dependency (`BenchmarkTools`, fwiw). I added `BenchmarkTools` to the project, moved it in the Project.toml file to `[extras]` and added it to the `[targets]  test =[ .... ]`  list, but still `BenchmarkTools`  was not found when running that test.

When I run the tests using `] test`, all tests pass. And, finally, after restarting VSCode (and thus all test servers), the tests pass as well.

Thus, it seems that something (at least a documentation warning) is required to inform the user that if the tests require a new test dependency, something else must be done, or the tests will fail until the test server is reinitialized. 

I append here an image of the state of the system with the error.

![image](https://user-images.githubusercontent.com/31046348/189365204-dfdc1c8b-40d4-4eb2-934c-d63e3de49418.png)

**Comment by davidanthoff** [comment] 2022-09-09 18:29
I'm pretty sure that is just a duplicate of https://github.com/julia-vscode/julia-vscode/issues/3022.

**Closed by davidanthoff** 2022-09-09 18:29 UTC
